name = "segov-dashboard"
main = "./src/worker.js"
account_id = "7395bec0ccb957ee527ff009d2b7a58b"
compatibility_date = "2026-08-05"

# Workers Static Assets
[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = false

# D1 Database (binding: env.DB)
[[d1_database]]
binding = "DB"
database_name = "segov-dados-politicos"
database_id = "48d9ba78-929f-4b0b-a1b1-00eeb12ae94b"

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://segov-dashboard.evanildobarros.workers.dev"

[observability]
enabled = true
